dist: trusty
language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
#install:
#  - ./gradlew -b ./openapi-generator/build.gradle clean generate
#  - ./gradlew -b ./openapi-generator/build.gradle install
script:
  - ./gradlew install jacocoTestReport coveralls -x javadoc
deploy:
  - provider: script
    skip_cleanup: true
    script: /bin/sh uploadArchives.sh
    on:
      branch: master
      jdk: oraclejdk8
  - provider: script
    skip_cleanup: true
    script: /bin/sh release.sh
    on:
      branch: release
      jdk: oraclejdk8
  - provider: script
    skip_cleanup: true
    script: /bin/sh sonarqube.sh
    on:
      branch: master
      jdk: oraclejdk9
before_install:
  - |
    if [ -z "${signingKeyId}" ]; then
      echo "No signing the artifacts"
    else
      echo "Signing artifacts"
      openssl aes-256-cbc -K $encrypted_98cf1ffdea51_key -iv $encrypted_98cf1ffdea51_iv -in nem2-sdk-java.gpg.enc -out nem2-sdk-java.gpg -d
    fi